  name: Splitter CI

  on:
    push:
    pull_request:
      branches:
        - main

  jobs:
    run-backend-tests:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Build and run Unit tests
          working-directory: backend
          run: mvn -ntp -B verify
